# Generated by Django 4.2 on 2023-04-13 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('uploaded_user', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='disliked_pets', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_pets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pet_name'],
            },
        ),
    ]
